steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      -  build
      -  -t
      -  gcr.io/${PROJECT_ID}/$_SERVICE_NAME
      -  .
    timeout: 2400s
  # Push the container image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      -  push
      -  "gcr.io/${PROJECT_ID}/$_SERVICE_NAME"
    timeout: 2400s

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
        - run
        - deploy
        - $_SERVICE_NAME
        - --image
        - "gcr.io/${PROJECT_ID}/$_SERVICE_NAME"
        - --region
        - $_REGION
        - --platform
        - managed
        - --allow-unauthenticated
        - --set-env-vars=GOOGLE_CLOUD_PROJECT=$_GOOGLE_CLOUD_PROJECT,GS_BUCKET_NAME=$_GS_BUCKET_NAME,CLOUDRUN_SERVICE_URL=$_CLOUDRUN_SERVICE_URL,DEBUG=$_DEBUG
        - --port
        - $_PORT
        - --max-instances
        - $_MAX_INSTANCES
        - --min-instances
        - "0"
        - --add-cloudsql-instances 
        - ${PROJECT_ID}:${_REGION}:${_CLOUD_SQL_INSTANCE_NAME}
    timeout: 2400s

timeout: 2400s

images:
- 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'

options:
  dynamicSubstitutions: true
