# Generated by Django 4.0.4 on 2022-09-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turageuser',
            name='national_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
