# Generated by Django 4.0.4 on 2022-10-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turageuser',
            options={'verbose_name': 'Turage User'},
        ),
        migrations.AddField(
            model_name='turageuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Passenger'), (2, 'Driver')], null=True),
        ),
    ]
