# Generated by Django 4.0.4 on 2022-09-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='number_passengers',
            field=models.IntegerField(default=1),
        ),
    ]
