# Generated by Django 4.0.4 on 2022-08-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='riding_requests',
        ),
        migrations.AddField(
            model_name='ridingrequest',
            name='passenger',
            field=models.ManyToManyField(blank=True, to='ride.passenger'),
        ),
    ]
