# Generated by Django 4.0.4 on 2022-10-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_alter_turageuser_options_turageuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='time_to_leave',
            field=models.DateTimeField(null=True),
        ),
    ]
