# Generated by Django 4.0.4 on 2022-10-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_alter_riderequest_number_passengers'),
        ('ride', '0002_alter_turageuser_national_id'),
    ]

    operations = [
    ]
