# Generated by Django 4.0.4 on 2022-08-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_remove_passenger_riding_requests_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RidingRequest',
            new_name='RideRequest',
        ),
    ]
