# Generated by Django 4.0.4 on 2022-08-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_rename_ridingrequest_riderequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='destination_waypoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_waypoint', to='ride.waypoint'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='origin_waypoint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_waypoint', to='ride.waypoint'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='time_requested',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='time_to_leave',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
