# Generated by Django 4.0.4 on 2022-10-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_merge_20221011_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turageuser',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
