# Generated by Django 4.0.4 on 2022-10-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_merge_20221004_1647'),
        ('ride', '0004_alter_turageuser_national_id'),
    ]

    operations = [
    ]
